### ISSUE TITLE
I need query builder in core php

### ISSUE THREAD

**Issue by dontKnew** [rexshijaku/sql-to-ci-builder#6]
I wants codeigniter 4/3 query builder class to use in core php project

**Comment by rexshijaku** [comment]
What's the issue @dontKnew with it?

**Comment by dontKnew** [comment]
> What's the issue @dontKnew with it?

This is your project convert SQL to codeigniter query builder , but I want to use direct codeigniter query builder in core php project.

And now I am using Laravel ORM Query Builder in core php project. Thats awesome 😋
